DROP TABLE IF EXISTS workouts CASCADE;
CREATE TABLE workouts (
    id SERIAL PRIMARY KEY NOT NULL,
    users_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    days_id INTEGER REFERENCES days(id) ON DELETE CASCADE,
    exercises_id INTEGER REFERENCES exercises(id) ON DELETE CASCADE,
    active_workout BOOLEAN DEFAULT TRUE
);
